language: cpp

sudo: false

# Build with gcc and clang.
compiler:
  - gcc
  - clang

addons:
  apt:
    packages: cmake

# Build both debug and release configurations, through use of an environment variable in the build matrix.
env:
  - CONFIGURATION=Debug
  - CONFIGURATION=Release

# Install SDL2
before_install:
  - |
    set -e
    wget https://www.libsdl.org/release/SDL2-2.0.4.tar.gz;
    tar -xzvf SDL2-2.0.4.tar.gz;
    cd SDL2-2.0.4 && ./configure --prefix=$HOME/SDL2 && make && make install;
  - export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:$HOME/SDL2

# Run cmake to generate makefiles in 'builds' directory.
# No need to create it because it's part of the repo.
# Pass along configuration type to cmake.
before_script:
  - cd builds
  - cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=$CONFIGURATION ..

# Run make in the directory containing generated makefiles.
script:
  - make test
