language: cpp

sudo: false

# Do not build branches of the form "pr/*". By prefixing pull requests coming
# from branches inside the repository with pr/, this avoids building both the
# branch push _and_ the pull request.
# Based on https://github.com/boostorg/hana/blob/master/.travis.yml
branches:
  except: /pr\/.*/

env:
  global:
  - secure: "Fvqq6eap91RcCLlMh+t/wStmxrp6YdQL4/ucqN2S1KEs3WIQsjrxC1cWAVcwhS5bPbGjdlX+B7uY5r/VRpmOBnXMR+TPBiLVr4ing/ZH6+QHcvib5+1LepAcwN32jaAaYk8q49ulD1jmDDKO6xXWHmRKoICTNfSWsnjsye+QNFd9Fpr/fw5VWjdPp0edgdTebWIPzLfqCfbhKrG3KtuXuh4wevduLyuozOfy9ZJMG5mOqDnrlMxkdacx8O5Pj2xOibPUd4sirsu0+73xHvr/K4CVtx3V2SSmH/wLI4Vbq1v/3/P4uUOzktvJbSh5OTNmtSuzuTE6hM6ExRvzRjtQp79EXg7mvtOMBlP+jz5Iy+d8q/qOv1m7ywqP3qvHAwS6o7U91swnTz6LWd6NXVDTV/zIlwFPXI645mfH+S2Fcn/aDzz/uAnA2O/I5l2s4UkgSawX5SFitLAonw5HLThyhn3S5n8urtW9ZMKKGzzQ4eNgTib14PEaHsbB7uzaGFT4K1evKK+YPm4tEQObOhsGFs1AZfWDo7oZ66wGid+MgV37biDG36MbhMODIyuM0uFQYys411ajXBrfHXBpWX/eVzrrlsU4S1UTKZSQdZ7wsTOFpL5pWYuwgF25pgABIw975fAZX7GPw3eTgrcybNNaNm84+zMUB4b2HDvLDvzrHv8="
  - SDL_VIDEODRIVER: dummy

# Build both debug and release configurations, through use of an environment variable in the build matrix.
matrix:
  include:
    - os: linux
      env: CONFIGURATION=Debug COMPILER=g++-5
      compiler: gcc
      addons: &gcc5
        apt:
          packages:
            - g++-5
            - cmake
            - ninja-build
          sources: &sources
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
            - kalakris-cmake
      cache: &sdl_cache
        directories:
          - $HOME/SDL2

    - os: linux
      env: CONFIGURATION=Release COMPILER=g++-5
      compiler: gcc
      addons: *gcc5
      cache: *sdl_cache

    - os: linux
      env: CONFIGURATION=Debug COMPILER=clang++-3.6
      compiler: clang
      addons: &clang36
        apt:
          packages:
            - clang-3.6
            - g++-5
            - cmake
            - ninja-build
          sources: *sources
      cache: *sdl_cache

    - os: linux
      env: CONFIGURATION=Release COMPILER=clang++-3.6
      compiler: clang
      addons: *clang36
      cache: *sdl_cache

    - os: osx
      env: CONFIGURATION=Debug COMPILER=clang++ DOCUMENTATION=true
      osx_image: xcode7

    - os: osx
      env: CONFIGURATION=Release COMPILER=clang++
      osx_image: xcode7

# Install SDL2
before_install:
  - set -e
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      if [ ! -d "$HOME/SDL2/lib" ]; then
          wget https://www.libsdl.org/release/SDL2-2.0.4.tar.gz;
          tar -xzf SDL2-2.0.4.tar.gz;
          cd SDL2-2.0.4 && ./configure --prefix=$HOME/SDL2 && make -j2 && make install;
      fi
      export SDL2DIR=$HOME/SDL2
    fi
  - |
    if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      brew update && brew install cmake sdl2 ninja;
      if [[ "${DOCUMENTATION}"  == "true" ]]; then
        brew install doxygen
      fi
    fi

# Run cmake to generate makefiles in 'builds' directory.
before_script:
  - cd $TRAVIS_BUILD_DIR
  - mkdir -p -v build
  - cd build
  - cmake -GNinja -DCMAKE_BUILD_TYPE=$CONFIGURATION -DCMAKE_CXX_COMPILER=$COMPILER ..

# Run make in the directory containing generated makefiles.
script:
  - cmake --build .
  - ctest -V

after_success:
  - |
    if [[ "${DOCUMENTATION}" == "true" ]]; then
      cmake --build . --target doc
      if [[ "${TRAVIS_PULL_REQUEST}" == "false" && "${TRAVIS_BRANCH}" == "master" ]]; then
        # Suppress output to avoid leaking the token when the command fails
        git clone https://tcbrindle:${GITHUB_TOKEN}@github.com/tcbrindle/sdlxx --depth 1 --branch=gh-pages gh-pages &>/dev/null
        rm -rf gh-pages/{search,*.png,*.css,*.js,*.html}
        cp -R doc/html/* gh-pages/
        pushd gh-pages/
        git config --global user.name "Travis Bot"
        git config --global user.email "travis@travis-ci.org"
        git add --all .
        git commit --allow-empty -m "Update to ${TRAVIS_COMMIT:0:7}"
        # Suppress output to avoid leaking the token
        travis_retry git push origin gh-pages &>/dev/null
        popd
      fi
    fi

notifications:
  email: false
