language: cpp

sudo: false

# Do not build branches of the form "pr/*". By prefixing pull requests coming
# from branches inside the repository with pr/, this avoids building both the
# branch push _and_ the pull request.
# Based on https://github.com/boostorg/hana/blob/master/.travis.yml
branches:
  except: /pr\/.*/

# Build both debug and release configurations, through use of an environment variable in the build matrix.
matrix:
  include:
    - os: linux
      env: CONFIGURATION=Debug COMPILER=g++-5
      compiler: gcc
      addons: &gcc5
        apt:
          packages:
            - g++-5
            - cmake
            - ninja-build
          sources: &sources
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
            - kalakris-cmake

    - os: linux
      env: CONFIGURATION=Release COMPILER=g++-5
      compiler: gcc
      addons: *gcc5

    - os: linux
      env: CONFIGURATION=Debug COMPILER=clang++-3.6
      compiler: clang
      addons: &clang36
        apt:
          packages:
            - clang-3.6
            - g++-5
            - cmake
            - ninja-build
          sources: *sources

    - os: linux
      env: CONFIGURATION=Release COMPILER=clang++-3.6
      compiler: clang
      addons: *clang36

    - os: osx
      env: CONFIGURATION=Debug COMPILER=clang++
      osx_image: xcode7

    - os: osx
      env: CONFIGURATION=Release COMPILER=clang++
      osx_image: xcode7

# Install SDL2
before_install:
  - set -e
  - |
    if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      brew update && brew install cmake ninja;
    fi

# Run cmake to generate makefiles in 'builds' directory.
before_script:
  - cd $TRAVIS_BUILD_DIR
  - mkdir -p -v build
  - cd build
  - cmake -GNinja -DCMAKE_BUILD_TYPE=$CONFIGURATION -DCMAKE_CXX_COMPILER=$COMPILER ..

# Run make in the directory containing generated makefiles.
script:
  - cmake --build .
  - ctest
