language: cpp

sudo: false

cache:
  directories:
    - $HOME/SDL2

# Build both debug and release configurations, through use of an environment variable in the build matrix.
matrix:
  include:
    - os: linux
      env: CONFIGURATION=Debug COMPILER=gcc-5
      compiler: gcc
      addons: &gcc5
        apt:
          packages:
            - cmake
            - g++-5
          sources: &sources
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
            - kalakris-cmake

    - os: linux
      env: CONFIGURATION=Release COMPILER=gcc-5
      compiler: gcc
      addons: *gcc5

    - os: linux
      env: CONFIGURATION=Debug COMPILER=clang-3.6
      compiler: clang
      addons: &clang36
        apt:
          packages:
            - cmake
            - clang-3.6
          sources: *sources

    - os: linux
      env: CONFIGURATION=Release COMPILER=clang-3.6
      compiler: clang
      addons: *clang36

    - os: osx
      env: CONFIGURATION=Debug COMPILER=clang++
      osx_image: xcode7

    - os: osx
      env: CONFIGURATION=Release COMPILER=clang++
      osx_image: xcode7

# Install SDL2
before_install:
  - set -e
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
        if [ ! -d "$HOME/SDL2/lib" ]; then
            wget https://www.libsdl.org/release/SDL2-2.0.4.tar.gz;
            tar -xzvf SDL2-2.0.4.tar.gz;
            cd SDL2-2.0.4 && ./configure --prefix=$HOME/SDL2 && make -j2 && make install;
        fi
    fi
  - export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:$HOME/SDL2

  - |
    if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      brew update && brew install cmake sdl2;
    fi

# Run cmake to generate makefiles in 'builds' directory.
before_script:
  - cd $TRAVIS_BUILD_DIR
  - mkdir -p -v build
  - cd build
  - cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=$CONFIGURATION -DCMAKE_CXX_COMPILER=$COMPILER ..

# Run make in the directory containing generated makefiles.
script:
  - make test
