
os:
  - Visual Studio 2015
  #- MinGW

configuration:
  - Debug
  - Release

install:
  - git submodule update --init
  - mkdir build
  - cd build
  - cmake -G "Visual Studio 14 2015" -DCMAKE_BUILD_TYPE=%CONFIGURATION% -Dgtest_force_shared_crt=ON ..

build_script:
  - cmake --build .
  - ctest
