
os:
  - Visual Studio 2015
  #- MinGW

configuration:
  - Debug
  - Release

install:
  - git submodule update --init
  - mkdir builds
  - cd builds
  - cmake -G "Visual Studio 14 2015" ../ && cd ..

build:
  project: builds/sdl++.sln
