
os: Visual Studio 2015

# Do not build branches of the form "pr/*". By prefixing pull requests coming
# from branches inside the repository with pr/, this avoids building both the
# branch push _and_ the pull request.
# Based on https://github.com/boostorg/hana/blob/master/.travis.yml
branches:
  except:
    - /pr\/.+/

environment:
  matrix:
    - platform: x86
      generator: Visual Studio 14

    - platform: x64
      generator: Visual Studio 14 Win64

configuration:
  - Debug
  - Release

install:
  - git submodule update --init
  - mkdir build
  - cd build
  - cmake -G "%generator%" -Dgtest_force_shared_crt=ON ..

build_script:
  - cmake --build . --config %CONFIGURATION%

test_script:
  - ctest -V
